\copy Actors from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/actors.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Aka_Names from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/aka_names.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Cast_List from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/cast.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Genres from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/genres.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Keywords from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/keywords.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Movies from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/movies.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Movie_Keyword from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/movies_keywords.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Movies_Genres from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/movies_genres.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
\copy Series from 'D:/schoolwork/Spring 2017/CS327E_databases/lab1/csv_dataset_full/series.csv' (header TRUE, format csv, delimiter ',', encoding 'UTF8');
